# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Learn' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Learn
  pod 'Alamofire', '~> 5.5'
  pod 'SwiftyJSON'
  pod 'FLEX', :configurations => ['Debug']
  pod 'SDWebImage', '~> 5.0'

end
