# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Learn' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Learn
  pod 'Alamofire', '~> 4.7.0'
  pod 'SwiftyJSON', '4.0.0'
  pod 'FLEX', '~> 2.0', :configurations => ['Debug'] 
  pod 'SDWebImage'

end
